In [1]:
import numpy as np


In [2]:
myPythonList = [1,12,77,31]
print(myPythonList)

[1, 12, 77, 31]


In [3]:
numpy_array_from_list = np.array(myPythonList)
numpy_array_from_list

array([ 1, 12, 77, 31])

In [4]:
a  = np.array([1,12,77,31])
print(a)

[ 1 12 77 31]


In [5]:
x=numpy_array_from_list + 20
print(x)

[21 32 97 51]


In [6]:
a  = np.array([1,2,3])
print(a.shape)
print(a.dtype)

(3,)
int32


In [7]:
b  = np.array([1.1,2.0,3.2])
print(b.dtype)

float64


In [8]:
c = np.array([(1,4,5),
              (8,7,6)])
print(c)

[[1 4 5]
 [8 7 6]]


In [9]:
d = np.array([
    [[1, 2,3],
        [4, 5, 6]],
    [[7, 8,9],
        [10, 11, 12]]
])
print(d.shape)
(2, 2, 3)

(2, 2, 3)


(2, 2, 3)

In [10]:
import numpy as np
x=np.zeros((2,2), dtype=np.int16)
print(x)


[[0 0]
 [0 0]]


In [11]:
import numpy as np
np.ones((1,2,3), dtype=np.int16)	

array([[[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [12]:
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
e.flatten()


array([1, 2, 3, 4, 5, 6])

In [14]:
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


In [15]:
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


In [16]:
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)			

[6.05675972 4.39958843 4.13893065 5.82796206 5.41161841 5.05150078
 4.28623065 5.59547211 5.38938919 4.84084576]


In [17]:
A = np.matrix(np.ones((4,4)))		
np.array(A)[2]=2  #immutable
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
np.arange(1, 11)	

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
import numpy as np
np.linspace(1.0, 10.0, num=20)


array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [20]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

In [21]:
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [22]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize	

16

In [23]:
import numpy as np
e  = np.array([(1,2,3), (4,5,6)])
print(e)

[[1 2 3]
 [4 5 6]]


In [24]:
### Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))


4.138930649258602
6.056759724431303
5.099829776419559
5.2204449842882035
0.6338475132248012


In [25]:
# Linear algebra
### Dot product: product of two arrays
f = np.array([1,2])
g = np.array([3,6])
### 1*4+2*5
np.dot(f, g)

15

In [26]:
### Matmul: matruc product of two arrays
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
### 1*5+2*7 = 19
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

In [27]:
# Taking a 3 * 3 matrix
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [28]:
# creating a 2X2 Numpy matrix
n_array = np.array([[50, 29], [30, 44]])
  
# Displaying the Matrix
print("Numpy Matrix is:")
print(n_array)
  
# calculating the determinant of matrix
det = np.linalg.det(n_array)
  
print("\nDeterminant of given 2X2 matrix:")
print(int(det))

Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given 2X2 matrix:
1330


In [29]:
# Let's create a square matrix (NxN matrix)
mx = np.array([[1,1,1],[0,1,2],[1,5,3]])

# Let's get rank of matrix 
np.linalg.matrix_rank(mx)

3

In [30]:
example_matrix = np.array([
  [1,2,3,4],
  [5,6,7,8],
  [9,10,11,12],
  [13,14,15,16]
])
eigenvalues, eigenvectors = np.linalg.eig(example_matrix)
print(eigenvalues, eigenvectors)

[ 3.62093727e+01 -2.20937271e+00 -2.57831463e-15  5.57979826e-17] [[-0.15115432  0.72704996  0.51747505 -0.06588506]
 [-0.34923733  0.28320876 -0.82375673 -0.31743721]
 [-0.54732033 -0.16063243  0.09508831  0.83252961]
 [-0.74540333 -0.60447363  0.21119337 -0.44920733]]


In [31]:
# make matrix with numpy
gfg = np.matrix('[6, 2; 3, 4]')
         
# applying matrix.diagonal() method
diag = gfg.diagonal()
   
print(diag)

[[6 4]]


In [32]:
# make matrix with numpy
gfg = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.transpose() method
trans = gfg.transpose()
    
print(trans)

[[ 4 12]
 [ 1  3]]


In [33]:
gfg = np.matrix('[4, 1; 12, 3]')
              
# applying matrix.trace() method
tracem = gfg.trace()
    
print(tracem)

[[7]]
